<!doctype html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <title>Document</title>
 </head>
 <body>
  <script>
		function fun(){
			var n=999;
			nAdd=function(){n++};
			return function(){
				console.log(n);
			}
		}
		var get=fun();
		//get: function(){ console.log(n); }
		get();//999
		nAdd();
		get();//1000

		//作业: 
		function fn(){
			for(var i=0,arr=[];i<3;i++){//?
				arr[i]=function(){console.log(i)}//只定义函数，但是函数没有调用，别混淆
			}//调用的时候还没return，函数console中的i已经变成3，前面两个函数console已被覆盖！！
			return arr;
		}
		var funs=fn();
		funs[0]();//?3返回数组：arr[0],arr[1],arr[2]
		funs[1]();//?3
		funs[2]();//?3
		console.log(funs);
	</script>
 </body>
</html>
<!-- 易错难点：1.找受保护变量i    i=3 
			   2.返回了什么函数    arr=[function(){console.log(i)},function(){console.log(i)},function(){console.log(i)}]   (该函数没有运行，所以里面的i一样返回)



-->